# https://kubernetes.io/docs/setup/cri/#cri-o
- name: configure YUM repository
  yum_repository:
    name: paas7-crio-311-candidate
    description: cri-o
    baseurl: https://cbs.centos.org/repos/paas7-crio-311-candidate/$basearch/os/
    skip_if_unavailable: yes
    gpgcheck: no
    enabled: no

- name: install packages
  yum:
    name:
    - cri-o
    - cri-tools
    - containernetworking-plugins
    state: present
    enablerepo: paas7-crio-311-candidate
  notify: restart crio

- name: mkdirs
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - /etc/systemd/system/crio.service.d
  - /opt/cni

- name: check if CNI bin dir exists
  stat: 
    path: /opt/cni/bin
  register: cni_bin_dir

- name: check if alternate CNI bin dir exists
  stat:
    path: /usr/libexec/cni
  register: cni_bin_dir2

- name: link CNI bin dir
  file:
    path: /opt/cni/bin
    state: link
    src: /usr/libexec/cni
  when: not cni_bin_dir.stat.exists and cni_bin_dir2.stat.exists

- name: create CNI bin dir
  file:
    path: /opt/cni/bin
    state: directory
  when: not cni_bin_dir.stat.exists and not cni_bin_dir2.stat.exists

- name: Enable kernel modules
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
  - br_netfilter

- name: Persist kernel modules
  copy:
    dest: "/etc/modules-load.d/crio-{{ item }}.conf"
    content: "{{ item }}"
  with_items:
  - br_netfilter

- name: Setup required sysctl params
  sysctl:
    sysctl_file: "/etc/sysctl.d/99-crio.conf"
    name: "{{ item }}"
    value: 1
    state: present
    reload: yes
  with_items:
  - net.ipv4.ip_forward
  - net.bridge.bridge-nf-call-iptables
  - net.bridge.bridge-nf-call-arptables
  - net.bridge.bridge-nf-call-ip6tables

- name: config
  template:
    dest: /etc/systemd/system/crio.service.d/proxy.conf
    src: crio-proxy.conf.j2
  when: crio_proxies
  notify: restart crio

- name: Make sure crio service is enabled and running
  systemd:
    name: crio
    daemon_reload: yes
    state: started
    enabled: yes

