- name: download kubernetes-node
  get_url:
    dest: /tmp/kubernetes-node-linux-amd64.tar.gz
    url: https://dl.k8s.io/v1.14.0/kubernetes-node-linux-amd64.tar.gz
    checksum: sha512:75dc99919d1084d7d471a53ab60c743dc399145c99e83f37c6ba3c241b2c0b2ecc2c0d1b94690ff912e2a15b7c5595aa1d2d24c2fc439e06d85ff0246fb43b89
  environment:
    http_proxy: "{{ kubelet_download_http_proxy | default('') }}"
    https_proxy: "{{ kubelet_download_http_proxy | default('') }}"

- name: unarchive
  unarchive:
    dest: /tmp
    src: /tmp/kubernetes-node-linux-amd64.tar.gz
    remote_src: yes

- name: install
  copy:
    dest: "/usr/local/bin/{{ item }}"
    src: "/tmp/kubernetes/node/bin/{{ item }}"
    remote_src: yes
    mode: 0755
  with_items:
  - kubelet
  - kubeadm
  notify: restart kubelet

- name: mkdirs
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - /etc/kubernetes/manifests
  - /var/lib/kubelet

- name: Enable br_netfilter module
  modprobe:
    name: br_netfilter
    state: present

- name: Persist br_netfilter module
  copy:
    dest: /etc/modules-load.d/k8s-kubelet.conf
    content: br_netfilter

- name: Modprode Kernel Module for IPVS
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - ip_vs
    - ip_vs_rr
    - ip_vs_wrr
    - ip_vs_sh
    - nf_conntrack

- name: Persist ip_vs modules
  copy:
    dest: /etc/modules-load.d/k8s-ipvs.conf
    content: |
      ip_vs
      ip_vs_rr
      ip_vs_wrr
      ip_vs_sh
      nf_conntrack

- name: Enable bridge-nf-call tables
  sysctl:
    name: "{{ item }}"
    state: present
    sysctl_file: "/etc/sysctl.d/99-k8s-kubelet.conf"
    value: 1
    reload: yes
  with_items:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-arptables
    - net.bridge.bridge-nf-call-ip6tables

# config net.ipv4.ip_local_reserved_ports

- name: service defaults
  template:
    dest: /etc/sysconfig/kubelet
    src: kubelet.default.env.j2
  notify: restart kubelet

- name: service
  template:
    dest: /etc/systemd/system/kubelet.service
    src: kubelet.service.j2
  notify: restart kubelet

- name: kubelet service
  systemd:
    name: kubelet
    state: started
    enabled: yes
    daemon_reload: yes

