- name: download kubernetes-node
  get_url:
    dest: /tmp/kubernetes-node-linux-amd64.tar.gz
    url: https://storage.googleapis.com/kubernetes-release/release/v1.15.1/kubernetes-node-linux-amd64.tar.gz
    checksum: sha256:6498aa35ababa367efb02ceef6ab387efcfef24febe6c9065cc19567499229b9
  environment:
    http_proxy: "{{ kubectl_download_http_proxy | default('') }}"
    https_proxy: "{{ kubectl_download_https_proxy | default('') }}"
- name: unarchive
  unarchive:
    dest: /tmp
    src: /tmp/kubernetes-node-linux-amd64.tar.gz
    remote_src: yes
- name: install
  copy:
    dest: "/usr/local/bin/{{ item }}"
    src: "/tmp/kubernetes/node/bin/{{ item }}"
    remote_src: yes
    mode: 0755
  with_items:
  - kubectl
