- name: download kubernetes-node
  get_url:
    dest: /tmp/kubernetes-node-linux-amd64.tar.gz
    url: https://storage.googleapis.com/kubernetes-release/release/v1.16.0/kubernetes-node-linux-amd64.tar.gz
    checksum: sha256:23f93b6b9967b22581869fd7b6f43506ccb2f522b63805cb77206b2ed183bc8b
  environment:
    http_proxy: "{{ kubectl_download_http_proxy | default('') }}"
    https_proxy: "{{ kubectl_download_https_proxy | default('') }}"
- name: unarchive
  unarchive:
    dest: /tmp
    src: /tmp/kubernetes-node-linux-amd64.tar.gz
    remote_src: yes
- name: install
  copy:
    dest: "/usr/local/bin/{{ item }}"
    src: "/tmp/kubernetes/node/bin/{{ item }}"
    remote_src: yes
    mode: 0755
  with_items:
  - kubectl
